sudo: required
services:
   - docker

before_install:
   - docker build -t marcusblankenship/react-test -f ./client/Dockerfile.dev ./client

script:
   - docker run -e CI=true marcusblankenship/react-test npm test 

after_success:
   - docker build -t marcusblankenship/multi-client ./client
   - docker build -t marcusblankenship/multi-server ./server
   - docker build -t marcusblankenship/multi-worker ./worker
   - docker build -t marcusblankenship/multi-nginx ./nginx
     
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

   - docker push marcusblankenship/multi-client
   - docker push marcusblankenship/multi-server
   - docker push marcusblankenship/multi-worker
   - docker push marcusblankenship/multi-nginx

deploy:
   edge: true
   artifact: Dockerrun.aws.json
   provider: elasticbeanstalk
   region: "us-east-1"
   app: "multi-docker4"
   env: "MultiDocker4-env"
   bucket_name: "elasticbeanstalk-us-east-1-716954889540"
   bucket_path: "multi-docker4"
   on:
      branch: "master"
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: 
      secure: $AWS_SECRET_KEY

  
   
